"use client";

import { ChangeEvent, useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { flavors } from "@/lib/catalog";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type AdminProduct = { id: string; name_en: string; name_ar: string; price_sar: number; image_url: string; inventory: number; active: boolean };
const previewProducts: AdminProduct[] = flavors.map((item) => ({ id: item.id, name_en: item.en, name_ar: item.ar, price_sar: item.priceSar, image_url: item.image, inventory: 0, active: true }));

export function AdminConsole() {
  const client = getSupabaseBrowserClient();
  const [user, setUser] = useState<User | null>(null);
  const [products, setProducts] = useState(previewProducts);
  const [selected, setSelected] = useState<AdminProduct>(previewProducts[0]);
  const [notice, setNotice] = useState(client ? "Checking admin access…" : "PREVIEW MODE · Connect a dedicated HUBB Supabase project to publish changes.");
  const isAdmin = user?.app_metadata?.role === "admin";
  useEffect(() => { if (!client) return; client.auth.getUser().then(async ({ data }) => { setUser(data.user); if (data.user?.app_metadata?.role !== "admin") { setNotice("Admin access requires app_metadata.role = admin."); return; } const result = await client.from("products").select("id,name_en,name_ar,price_sar,image_url,inventory,active").order("sort_order"); if (result.error) setNotice(result.error.message); else if (result.data) { setProducts(result.data as AdminProduct[]); setSelected(result.data[0] as AdminProduct); setNotice("LIVE COMMERCE DATA"); } }); }, [client]);
  const updateField = (key: keyof AdminProduct, value: string | number | boolean) => setSelected((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!client || !isAdmin) { setNotice("Preview saved in this screen only. Connect Supabase and sign in as admin to publish."); setProducts((current) => current.map((item) => item.id === selected.id ? selected : item)); return; } const result = await client.from("products").update({ name_en: selected.name_en, name_ar: selected.name_ar, price_sar: selected.price_sar, image_url: selected.image_url, inventory: selected.inventory, active: selected.active }).eq("id", selected.id); setNotice(result.error?.message || "Published securely."); if (!result.error) setProducts((current) => current.map((item) => item.id === selected.id ? selected : item)); };
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !client || !isAdmin) { setNotice("Live media upload requires an authenticated HUBB admin."); return; } const path = `products/${selected.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const result = await client.storage.from("product-media").upload(path, file, { upsert: false }); if (result.error) { setNotice(result.error.message); return; } const { data } = client.storage.from("product-media").getPublicUrl(path); updateField("image_url", data.publicUrl); setNotice("Upload ready. Press Publish changes to assign it."); };
  return <main className="page-main admin-page"><header><div><p>HUBB COMMERCE STUDIO · لوحة الإدارة</p><h1>CHANGE THE STORE.<br /><em>KEEP THE SOUL.</em></h1></div><span>{notice}</span></header><div className="admin-layout"><nav><p>PRODUCTS / 7</p>{products.map((item, index) => <button className={selected.id === item.id ? "is-active" : ""} onClick={() => setSelected(item)} key={item.id}><span>0{index + 1}</span><img src={item.image_url} alt="" /><b>{item.name_ar}<small>{item.name_en}</small></b><i>{item.active ? "LIVE" : "HIDDEN"}</i></button>)}<p>CONTENT</p><button><span>◉</span><b>Home film<small>Video slot</small></b><i>1</i></button><button><span>✎</span><b>Journal<small>Articles</small></b><i>3</i></button><button><span>▧</span><b>Orders<small>Customer orders</small></b><i>—</i></button></nav><section className="admin-editor"><div className="editor-preview"><img src={selected.image_url} alt={`${selected.name_en} preview`} /><label>REPLACE PACK IMAGE<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} /></label><small>WebP/JPEG · 4:5 · real product photography or approved pack render</small></div><div className="editor-fields"><p>PRODUCT / {selected.id.toUpperCase()}</p><label>ARABIC NAME<input value={selected.name_ar} onChange={(event) => updateField("name_ar", event.target.value)} dir="rtl" /></label><label>ENGLISH NAME<input value={selected.name_en} onChange={(event) => updateField("name_en", event.target.value)} /></label><div><label>PRICE / SAR<input type="number" min="0" step="0.01" value={selected.price_sar} onChange={(event) => updateField("price_sar", Number(event.target.value))} /></label><label>INVENTORY<input type="number" min="0" value={selected.inventory} onChange={(event) => updateField("inventory", Number(event.target.value))} /></label></div><label>IMAGE URL<input value={selected.image_url} onChange={(event) => updateField("image_url", event.target.value)} /></label><label className="active-toggle"><input type="checkbox" checked={selected.active} onChange={(event) => updateField("active", event.target.checked)} /><span /> PRODUCT VISIBLE IN STORE</label><button onClick={save}>PUBLISH CHANGES ↗</button><small>Prices are always re-read by the secure order function. The browser never controls the final charged amount.</small></div></section></div></main>;
}
